name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'  # Ganti dengan versi PHP yang kamu gunakan

      - name: Install dependencies
        run: composer install  # Jalankan jika proyek menggunakan Composer

      - name: Run tests
        run: vendor/bin/phpunit  # Jalankan unit test jika menggunakan PHPUnit
