name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: none  # Matikan coverage jika tidak diperlukan

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-interaction

      - name: Check vendor directory
        run: ls -la vendor/

      - name: Check PHPUnit version
        run: php vendor/bin/phpunit --version

      - name: Make PHPUnit executable
        run: chmod +x vendor/bin/phpunit

      - name: Run tests
        run: php vendor/bin/phpunit
